import { step } from './step'

// Node network whose links and nodes connect.
export default function AiAuditVisual() {
  return (
    <svg
      viewBox="0 0 120 80"
      fill="none"
      aria-hidden="true"
      className="qclay-offer-visual"
    >
      <line
        className="qov-shape"
        style={step(0)}
        x1="24"
        y1="24"
        x2="60"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
        opacity="0.5"
      />
      <line
        className="qov-shape"
        style={step(0)}
        x1="24"
        y1="56"
        x2="60"
        y2="40"
        stroke="currentColor"
        strokeWidth="2"
        opacity="0.5"
      />
      <line
        className="qov-shape"
        style={step(1)}
        x1="60"
        y1="40"
        x2="96"
        y2="24"
        stroke="currentColor"
        strokeWidth="2"
        opacity="0.5"
      />
      <line
        className="qov-shape"
        style={step(1)}
        x1="60"
        y1="40"
        x2="96"
        y2="56"
        stroke="currentColor"
        strokeWidth="2"
        opacity="0.5"
      />
      <circle
        className="qov-shape"
        style={step(2)}
        cx="24"
        cy="24"
        r="5"
        fill="currentColor"
      />
      <circle
        className="qov-shape"
        style={step(2)}
        cx="24"
        cy="56"
        r="5"
        fill="currentColor"
      />
      <circle
        className="qov-shape"
        style={step(3)}
        cx="60"
        cy="40"
        r="7"
        fill="currentColor"
      />
      <circle
        className="qov-shape"
        style={step(4)}
        cx="96"
        cy="24"
        r="5"
        fill="currentColor"
        opacity="0.7"
      />
      <circle
        className="qov-shape"
        style={step(4)}
        cx="96"
        cy="56"
        r="5"
        fill="currentColor"
        opacity="0.7"
      />
    </svg>
  )
}
