import { step } from './step'

// Browser window whose content blocks assemble row by row.
export default function SiteWebVisual() {
  return (
    <svg
      viewBox="0 0 120 80"
      fill="none"
      aria-hidden="true"
      className="qclay-offer-visual"
    >
      <rect
        className="qov-shape"
        style={step(0)}
        x="9"
        y="11"
        width="102"
        height="58"
        rx="7"
        stroke="currentColor"
        strokeWidth="2"
      />
      <line
        className="qov-shape"
        style={step(1)}
        x1="9"
        y1="25"
        x2="111"
        y2="25"
        stroke="currentColor"
        strokeWidth="2"
      />
      <circle
        className="qov-shape"
        style={step(1)}
        cx="17"
        cy="18"
        r="1.8"
        fill="currentColor"
      />
      <circle
        className="qov-shape"
        style={step(1)}
        cx="24"
        cy="18"
        r="1.8"
        fill="currentColor"
      />
      <circle
        className="qov-shape"
        style={step(1)}
        cx="31"
        cy="18"
        r="1.8"
        fill="currentColor"
      />
      <rect
        className="qov-shape"
        style={step(2)}
        x="18"
        y="34"
        width="46"
        height="6"
        rx="3"
        fill="currentColor"
      />
      <rect
        className="qov-shape"
        style={step(3)}
        x="18"
        y="45"
        width="84"
        height="4"
        rx="2"
        fill="currentColor"
        opacity="0.55"
      />
      <rect
        className="qov-shape"
        style={step(4)}
        x="18"
        y="54"
        width="64"
        height="4"
        rx="2"
        fill="currentColor"
        opacity="0.4"
      />
    </svg>
  )
}
